In [29]:
import pandas as pd

In [3]:
catalog.list()

[
    'orders',
    'companies',
    'reviews',
    'shuttles',
    'preprocessed_orders',
    'preprocessed_companies',
    'preprocessed_shuttles',
    'model_input_table',
    'regressor',
    'parameters',
    'params:model_options',
    'params:model_options.test_size',
    'params:model_options.random_state',
    'params:model_options.features'
]

In [75]:
orders = catalog.load("orders")

# Eliminar registros identicos
orders = orders.drop_duplicates()

# Eliminar fechas invalidas
orders = orders[orders['created_at'].str.len() == 20]

# Casteo la fecha y extraigo la hora
orders.loc[:, 'created_at_dt'] = pd.to_datetime(orders['created_at'])
orders['hour'] = orders['created_at_dt'].dt.hour
orders

[08/29/23 04:37:27] INFO     Loading data from 'orders' (CSVDataSet)...                         ]8;id=756283;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=795446;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\site-packages\kedro\io\data_catalog.py#475\475]8;;\

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,created_at,taken,created_at_dt,hour
0,14364873,30000009,2.478101,-72.719360,4200,2017-09-07T20:02:17Z,0,2017-09-07 20:02:17+00:00,20
1,14370123,30000058,0.451711,37.754761,4200,2017-09-07T20:13:16Z,0,2017-09-07 20:13:16+00:00,20
2,14368534,900003684,2.026072,207.191162,4000,2017-09-07T20:07:23Z,0,2017-09-07 20:07:23+00:00,20
3,14370258,900014452,2.671432,1.722656,4400,2017-09-07T20:15:19Z,1,2017-09-07 20:15:19+00:00,20
4,14369923,900014085,0.965496,117.429199,3450,2017-09-07T20:12:14Z,1,2017-09-07 20:12:14+00:00,20
...,...,...,...,...,...,...,...,...,...
93865,15795441,900006875,0.258742,3.819824,5200,2017-10-02T19:51:03Z,1,2017-10-02 19:51:03+00:00,19
93866,15796367,900008202,3.003163,51.203247,3850,2017-10-02T19:52:05Z,1,2017-10-02 19:52:05+00:00,19
93867,15793747,900004326,2.386920,185.627686,5700,2017-10-02T19:52:05Z,1,2017-10-02 19:52:05+00:00,19
93868,15796398,900015780,0.649980,-65.237671,6200,2017-10-02T19:52:05Z,1,2017-10-02 19:52:05+00:00,19
93869,15796660,900014003,0.208143,-1.466919,4200,2017-10-02T19:54:05Z,1,2017-10-02 19:54:05+00:00,19

In [46]:
orders.head(10)

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,created_at,taken,created_at_dt,hour
0,14364873,30000009,2.478101,-72.719360,4200,2017-09-07T20:02:17Z,0,2017-09-07 20:02:17+00:00,20
1,14370123,30000058,0.451711,37.754761,4200,2017-09-07T20:13:16Z,0,2017-09-07 20:13:16+00:00,20
2,14368534,900003684,2.026072,207.191162,4000,2017-09-07T20:07:23Z,0,2017-09-07 20:07:23+00:00,20
3,14370258,900014452,2.671432,1.722656,4400,2017-09-07T20:15:19Z,1,2017-09-07 20:15:19+00:00,20
4,14369923,900014085,0.965496,117.429199,3450,2017-09-07T20:12:14Z,1,2017-09-07 20:12:14+00:00,20
5,14367859,900004363,0.577156,-7.895874,5200,2017-09-07T20:13:16Z,1,2017-09-07 20:13:16+00:00,20
6,14367634,900006875,2.558039,4.086182,4200,2017-09-07T20:07:23Z,0,2017-09-07 20:07:23+00:00,20
7,14369615,900005637,1.145407,-33.873657,3200,2017-09-07T20:10:15Z,1,2017-09-07 20:10:15+00:00,20
8,14368621,900007609,1.218742,132.342285,4200,2017-09-07T20:14:14Z,1,2017-09-07 20:14:14+00:00,20
9,14367450,900004941,1.282540,0.792480,3200,2017-09-07T19:56:22Z,0,2017-09-07 19:56:22+00:00,19

In [52]:
orders = catalog.load("orders")

# Eliminar registros identicos
orders = orders.drop_duplicates()

# Eliminar fechas invalidas
orders = orders[orders['created_at'].str.len() == 20]

# calculo ratio de pedidos aceptados
stores['d'] = pd.DataFrame(orders.groupby('store_id')['taken'].agg('mean') * 100).reset_index()

[08/29/23 04:21:27] INFO     Loading data from 'orders' (CSVDataSet)...                         ]8;id=341215;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=782088;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\site-packages\kedro\io\data_catalog.py#475\475]8;;\

In [73]:
store_features = pd.DataFrame(orders.groupby('store_id')['taken'].agg(taken_percentage='mean') * 100).reset_index()

In [77]:
import mkl-random
mkl-random.version.version

â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚ import mkl-random                                                                                â”‚
â”‚           â–²                                                                                      â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯
SyntaxError: invalid syntax

In [74]:
model_input_table = orders.merge(store_features, left_on="store_id", right_on="store_id")
model_input_table = model_input_table.dropna()
model_input_table

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,created_at,taken,d,taken_percentage
0,14364873,30000009,2.478101,-72.719360,4200,2017-09-07T20:02:17Z,0,90.714286,90.714286
1,14820671,30000009,1.536888,246.942139,5500,2017-09-15T22:23:48Z,1,90.714286,90.714286
2,15524196,30000009,1.940923,-37.450806,3200,2017-09-28T13:30:00Z,1,90.714286,90.714286
3,14747337,30000009,0.661448,-5.360474,7500,2017-09-14T19:10:09Z,1,90.714286,90.714286
4,15274540,30000009,1.434018,150.468872,7200,2017-09-23T20:17:05Z,1,90.714286,90.714286
...,...,...,...,...,...,...,...,...,...
93865,15798024,900016166,1.090082,71.223267,3200,2017-10-02T20:42:04Z,1,100.000000,100.000000
93866,14779075,900016684,2.288364,-237.045654,5900,2017-09-15T13:01:10Z,1,100.000000,100.000000
93867,15810235,900014656,1.684666,-24.224487,4200,2017-10-03T10:45:55Z,1,100.000000,100.000000
93868,14734394,30000033,1.926091,-70.520264,5000,2017-09-14T14:40:06Z,1,100.000000,100.000000
93869,15869188,900016638,2.153837,42.957764,3750,2017-10-04T13:14:03Z,1,100.000000,100.000000

In [21]:
#15795869
orders[orders['order_id']==15795869]

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,created_at,taken
93870,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
93968,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
94066,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
94164,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
94262,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
...,...,...,...,...,...,...,...
126406,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
126504,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
126602,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
126700,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1
126798,15795869,900007604,0.583228,74.703247,3200,2017-10-02T19:55017-09-27T12:16:57Z,1

In [11]:
orders.shape

(126868, 7)

In [8]:
orders2 = orders.drop_duplicates()
orders2.shape

(93871, 7)

In [37]:
orders3 = orders2[orders2['created_at'].str.len() == 20]

In [22]:
orders3.shape

(93870, 7)

In [36]:
orders3.head()

,order_id,store_id,to_user_distance,to_user_elevation,total_earning,created_at,taken,created_at_dt
0,14364873,30000009,2.478101,-72.719360,4200,2017-09-07T20:02:17Z,0,2017-09-07 20:02:17+00:00
1,14370123,30000058,0.451711,37.754761,4200,2017-09-07T20:13:16Z,0,2017-09-07 20:13:16+00:00
2,14368534,900003684,2.026072,207.191162,4000,2017-09-07T20:07:23Z,0,2017-09-07 20:07:23+00:00
3,14370258,900014452,2.671432,1.722656,4400,2017-09-07T20:15:19Z,1,2017-09-07 20:15:19+00:00
4,14369923,900014085,0.965496,117.429199,3450,2017-09-07T20:12:14Z,1,2017-09-07 20:12:14+00:00

In [40]:
orders3.loc[:, 'created_at_dt'] = pd.to_datetime(orders3['created_at'])

[08/29/23 04:10:48] WARNING  C:\Users\User\AppData\Local\Temp\ipykernel_19380\818375551.py:1:       ]8;id=358661;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\warnings.py\warnings.py]8;;\:]8;id=477819;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\warnings.py#109\109]8;;\
                             SettingWithCopyWarning:
                             A value is trying to be set on a copy of a slice from a DataFrame.
                             Try using .loc[row_indexer,col_indexer] = value instead

                             See the caveats in the documentation:
                             https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#
                             returning-a-view-versus-a-copy
                               orders3.loc[:, 'created_at_dt'] =
                             pd.to_datetime(orders3['created_at'])

                    WARNING  C:\Users\User\AppData\Local\Temp\ipykernel_19380\818375551.py:1:       ]8;id=197978;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\warnings.py\warnings.py]8;;\:]8;id=587392;file://C:\Users\User\anaconda3\envs\kedro-environment\lib\warnings.py#109\109]8;;\
                             DeprecationWarning: In a future version, `df.iloc[:, i] = newvals`
                             will attempt to set the values inplace instead of always setting a new
                             array. To retain the old behavior, use either `df[df.columns[i]] =
                             newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
                               orders3.loc[:, 'created_at_dt'] =
                             pd.to_datetime(orders3['created_at'])